# Generated by Django 4.2.16 on 2024-11-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='location_context',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='usage_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
