# Generated by Django 4.2.16 on 2025-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_abstractuserprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuserprofile',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
